all: 1-modelo.pdf 1-practica.pdf

1-modelo.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/teorica/1-modelo.pdf

1-practica.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/practica/1-practica.zip
	unzip 1-practica.zip
	rm 1-practica.zip
