all: 5-tiemopo.pdf 5-practica.zip

5-tiempo.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/teorica/5-tiempo.pdf

5-practica.zip:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/practica/5-practica.zip
