all: 2-dato.pdf 2-practica.pdf

2-dato.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/teorica/2-dato.pdf

2-practica.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/practica/2-practica.zip
	unzip 2-practica.zip
	rm 2-practica.zip
