all: 4-causa.pdf 4-practica.pdf

4-causa.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/teorica/4-causa.pdf

4-practica.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/practica/4-practica.pdf
