all: 3-flujo.pdf 3-practica.pdf

3-flujo.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/teorica/3-flujo.pdf

3-practica.pdf:
	wget https://github.com/MetodosBayesianos/IBC1.2024.2/releases/download/practica/3-practica.zip
	unzip 3-practica.zip
	rm 3-practica.zip
